name: RandomBattle
main: me.merdril.RandomBattle.RandomBattle
version: 0.4.1
author: Mark Aligbe
depend: [Spout]
commands:
    regbattle:
        description: Adds this player to the list of players subject to random battles.
        permission: RandomBattle.regbattle
        usage: /regbattle <player>
    unregbattle:
        description: Remove the player from the list of players subject to random battles.
        permission: RandomBattle.regbattle.others
        usage: /unregbattle <player>
    stopbattles:
        description: Stop any further random battles from occuring server wide.
        permission: RandomBattle.stopbattles
        usage: /stopbattles
    resumebattles:
        description: Resume RandomBattle, if it was stopped.
        permission: RandomBattle.stopbattles
        usage: /resumebattles
    showregplayers:
        description: Shows registered players.
        permission: RandomBattle.debug.show
        usage: /showregplayers
    showspoutplayers:
        description: Show spout players.
        permission: RandomBattle.debug.show
        usage: /showspoutplayers
    removeblocks:
        description: Remove the blocks created by Random Battle.
        permission: RandomBattle.remove
        usage: /removeblocks